//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary_2._7._18_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string book_name { get; set; }
        public string book_author { get; set; }
        public string book_ISBN { get; set; }
        public Nullable<int> book_paper { get; set; }
        public string book_photo { get; set; }
    }
}
